Replace acme.png with demo.png
hedgedoc/react-client pull request #1089
Opened 2021-03-06 17:00 UTC by mrdrogdrog

### Component/Part
Demo branding

### Description
This PR changes the content of acme.png and renames it to demo.png

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

2021-03-07 09:36 UTC, DerMolly approved these changes

2021-03-07 11:11 UTC, DerMolly approved these changes

2021-03-09 21:27 UTC, ErikMichelson requested changes
I see no demo.png in /public/img.

2021-03-09 21:28 UTC, ErikMichelson approved these changes

2021-03-09 22:03 UTC, merged