Remove browserstack integration
hedgedoc/react-client pull request #1187
Opened 2021-04-11 20:38 UTC by mrdrogdrog

### Component/Part
E2E Tests

### Description
This PR removes the Browserstack integration.
We hoped to decrease the test run time by splitting the work load into build&serve with gh actions and run the browsers with browserstack. Well. It didn't work out. The has been almost no difference in the run time. Also browserstack failed sometimes (e.g. if all test runner were already busy) and reported "everything's okay" back to the CI.

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

2021-04-11 20:47 UTC, ErikMichelson requested changes

2021-04-11 20:47 UTC, ErikMichelson commented on .github/workflows/e2e.yml
> +                  - uses: cypress-io/github-action@v2
Indentation wrong and a list entry too much.

2021-04-12 20:04 UTC, DerMolly approved these changes

2021-04-13 17:48 UTC, ErikMichelson approved these changes

2021-04-13 19:20 UTC, merged