Fix splitter
hedgedoc/react-client pull request #1307
Opened 2021-06-09 13:53 UTC by mrdrogdrog

### Component/Part
Split component

### Description
This PR fixes the split component. If you stop holding down your mouse button while the mouse is not on the document after starting the resizing mode, then the splitter isn't stuck in resizing mode anymore.
You can also move your mouse over the whole document to resize the split.

### Steps

- [x] Added implementation
- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

2021-06-10 21:12 UTC, ErikMichelson requested changes
When dragging the splitter and you're leaving and re-entering the document area, the splitter extends only in one direction.


https://user-images.githubusercontent.com/52606896/121597670-47219400-ca41-11eb-8bc8-ffae781002a6.mp4

2021-06-11 13:44 UTC, mrdrogdrog commented on src/components/editor-page/editor-page.tsx
> +        onTaskCheckedChange={SetCheckboxInMarkdownContent}
Don't know. I fixed it.

2021-06-11 13:47 UTC, mrdrogdrog commented
@ErikMichelson I also fixed the resizing issue

2021-06-11 19:20 UTC, ErikMichelson approved these changes

2021-06-12 12:56 UTC, DerMolly approved these changes
LGM

2021-06-12 14:20 UTC, merged