Deduplicate CommonModal Props
hedgedoc/react-client pull request #1649
Opened 2021-11-21 14:06 UTC by mrdrogdrog

### Component/Part
Modals

### Description
This PR reworks the Props of the most modals by:
  - Renaming some of the props to make their intend a bit more clear
  - Remove some duplicated props that contain "show" and "onHide"

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

2021-11-21 14:20 UTC, DerMolly requested changes

2021-11-21 14:20 UTC, DerMolly commented on src/components/editor-page/app-bar/help-button/help-modal.tsx
> +      title={'editor.documentBar.help'}>
This does remove the selectedTab title…

2021-11-21 14:30 UTC, DerMolly approved these changes

2021-11-26 20:50 UTC, ErikMichelson approved these changes

2021-11-26 20:51 UTC, merged