Move markdown split into redux
hedgedoc/react-client pull request #1681
Opened 2021-12-10 17:32 UTC by mrdrogdrog

### Component/Part
Markdown content storage

### Description
This PR
  - moves the split of the markdown content by lines into the redux to reduce redundant splits
  - moves the trim of the markdown content into the editor to reduce the amount of transfered text

### Steps

- [x] Added implementation
- [ ] Added / updated tests
- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

2021-12-10 20:15 UTC, DerMolly requested changes

2021-12-10 20:17 UTC, mrdrogdrog commented on src/components/intro-page/intro-page.tsx
> +            markdownContentLines={introPageContent as string[]}
Why? The content of the array is wrong and it can't be undefined because it's capsuled by ShowIf

2021-12-10 20:19 UTC, mrdrogdrog commented on src/components/intro-page/intro-page.tsx
> +            markdownContentLines={introPageContent as string[]}
So: no. I won't change it because the type cast is more accurate

2021-12-10 20:29 UTC, mrdrogdrog commented on src/components/intro-page/intro-page.tsx
> +            markdownContentLines={introPageContent as string[]}
Also I changed that code

2021-12-10 21:10 UTC, DerMolly approved these changes

2021-12-14 09:08 UTC, ErikMichelson approved these changes

2021-12-14 09:16 UTC, merged