refactor: Deduplicate delete modal
hedgedoc/react-client pull request #1734
Opened 2021-12-30 19:54 UTC by DerMolly

### Component/Part
Note deletion modal

### Description
This PR removed duplicate note deletion modal

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### Related Issue(s)
fixes #1731

2022-01-26 16:35 UTC, ErikMichelson requested changes
When deleting notes from the history page that are untitled, the deletion modal has en empty note title instead of the "Untitled" fallback.

2022-01-26 16:35 UTC, ErikMichelson commented on src/components/editor-page/sidebar/delete-note-sidebar-entry/delete-note-modal.tsx
> +        <li {...cypressId('sidebar.deleteNote.modal.noteTitle')}>&nbsp;{optionalNoteTitle ?? noteTitle}</li>
Why is there this protected space?

2022-01-30 12:21 UTC, DerMolly commented on src/components/editor-page/sidebar/delete-note-sidebar-entry/delete-note-modal.tsx
> +        <li {...cypressId('sidebar.deleteNote.modal.noteTitle')}>&nbsp;{optionalNoteTitle ?? noteTitle}</li>
Not sure, I'll remove it.

2022-01-30 12:36 UTC, DerMolly commented
>When deleting notes from the history page that are untitled, the deletion modal has en empty note title instead of the "Untitled" fallback.

fixed

2022-01-30 12:50 UTC, ErikMichelson approved these changes

2022-02-13 11:30 UTC, mrdrogdrog approved these changes

2022-02-13 23:44 UTC, merged