Toolbar into redux
hedgedoc/react-client pull request #1763
Opened 2022-01-09 15:11 UTC by mrdrogdrog

### Component/Part
Editor Toolbar

### Description
This PR hooks the toolbar directly to the redux state instead of the editor.

### Steps

- [x] Added implementation
- [ ] Added / updated tests
- [ ] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### Additional Information
- This breaks the undo-management of codemirror. But since y-js has it's own undo manager this shouldn't be important.
-

2022-01-23 20:11 UTC, DerMolly approved these changes

2022-01-23 20:23 UTC, DerMolly approved these changes

2022-01-23 23:39 UTC, ErikMichelson requested changes

2022-01-23 23:39 UTC, ErikMichelson commented on src/components/editor-page/editor-pane/tool-bar/utils/codefenceDetection.ts
> + * Checks if the current
ESDoc incomplete

2022-01-23 23:39 UTC, ErikMichelson commented on src/redux/index.ts
> +export const getGlobalState = () => store.getState()
missing return type annotation?

2022-01-23 23:41 UTC, ErikMichelson commented
The translation `editor.editorToolbar.table.size` is missing or has an invalid key prefix.

2022-01-26 16:04 UTC, ErikMichelson approved these changes

2022-01-26 16:14 UTC, merged