Test markdown extensions
hedgedoc/react-client pull request #1886
Opened 2022-02-27 22:09 UTC by mrdrogdrog

### Component/Part
Markdown extensions

### Description
This PR adds new missing tests for the markdown extensions. It also replaces some cypress tests.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] Added / updated documentation
- [ ] Extended changelog
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### Related Issue(s)
#1161

2022-04-18 18:06 UTC, DerMolly requested changes

2022-04-18 18:35 UTC, DerMolly approved these changes

2022-04-18 19:09 UTC, DerMolly approved these changes

2022-04-19 09:02 UTC, ErikMichelson commented on src/components/markdown-renderer/markdown-extension/vimeo/vimeo-frame.test.tsx
> +    const view = render(<VimeoFrame id={'valid youtube id'} />)
```suggestion
    const view = render(<VimeoFrame id={'valid vimeo id'} />)
```

2022-04-19 09:05 UTC, ErikMichelson commented on src/components/markdown-renderer/markdown-extension/vimeo/__snapshots__/vimeo-frame.test.tsx.snap
> +        title="vimeo video of valid youtube id"
```suggestion
        src="https://player.vimeo.com/video/valid vimeo id?autoplay=1"
        title="vimeo video of valid vimeo id"
```

2022-04-19 16:18 UTC, mrdrogdrog commented on src/components/markdown-renderer/markdown-extension/vimeo/replace-vimeo-link.ts
>  const protocolRegex = /(?:http(?:s)?:\/\/)?/
It could. But I'm not sure if we actually achieve anything with that :shrug:

2022-04-19 21:18 UTC, ErikMichelson requested changes
Tests failing

2022-04-27 07:00 UTC, DerMolly commented
I fixed the bug in the jest tests. It's a bit unfortunate that the snapshots has to contain a space at the end, which can be autoremoved by some texteditors / IDEs.

2022-04-27 07:44 UTC, ErikMichelson approved these changes

2022-04-27 07:59 UTC, merged