Note loading boundary
hedgedoc/react-client pull request #2040
Opened 2022-05-09 21:04 UTC by mrdrogdrog

### Component/Part
Note loading

### Description
This PR adds a note loading boundary that fetches a note from the backend and saves it into the redux state before the editor is shown.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

2022-05-10 16:16 UTC, ErikMichelson commented
For better understanding some screenshots:

**Before this PR**
![image](https://user-images.githubusercontent.com/52606896/167674858-b9bc79de-78a2-4219-bf16-adc8b35679b0.png)

**With this PR**
![image](https://user-images.githubusercontent.com/52606896/167674961-dca8fe11-7b51-4787-b74a-9455b7416ca7.png)

**Normal 404 route (did not change by this PR)**
![image](https://user-images.githubusercontent.com/52606896/167675047-4a75e435-51ea-454e-8fa1-ee1d35544d91.png)

2022-05-10 16:17 UTC, ErikMichelson requested changes

2022-05-10 16:17 UTC, ErikMichelson commented on src/components/common/note-loading-boundary/hooks/use-load-note-from-server.ts
> +      throw new Error('Error while fetching note from server.\n' + (error as Error).message)
This should not be hardcoded if displayed in the UI. We've got a translation key for that purpose.

2022-05-10 16:26 UTC, mrdrogdrog commented
@ErikMichelson 

This is.. i don't wanna say "intended" but at least known. This pull requests solves a technical problem. The ui/ux situation is another topic and should be solved when we finally have a design approach.

2022-05-10 21:46 UTC, DerMolly approved these changes

2022-05-11 09:42 UTC, ErikMichelson commented on src/components/common/note-loading-boundary/note-loading-boundary.tsx
> +        descriptionI18nKey={error.message}></CommonErrorPage>
Is there anything prohibiting this?

```suggestion
        descriptionI18nKey={error.message} />
```

2022-05-11 09:50 UTC, mrdrogdrog commented
@ErikMichelson huh. interesting. Usually eslint complains when this happens. :shrug:

2022-05-11 09:57 UTC, ErikMichelson approved these changes

2022-05-11 10:47 UTC, merged