Remove non-existing css class reference in splitter
hedgedoc/react-client pull request #2229
Opened 2022-07-23 11:12 UTC by ErikMichelson

### Component/Part
Splitter

### Description
The splitter referenced an old css class '.splitter > .right' that doesn't exist anymore.
The HTML dom therefore rendered the right side of the splitter with an class name of 'undefined'.
This PR removes the invalid reference.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### Related Issue(s)
none

2022-07-23 11:18 UTC, mrdrogdrog approved these changes

2022-07-24 10:18 UTC, DerMolly requested changes

2022-07-24 10:18 UTC, DerMolly commented on src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap
> +      class="splitter "
```suggestion
      class="splitter"
```

2022-07-24 10:18 UTC, DerMolly commented on src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap
> +      class="splitter "
```suggestion
      class="splitter"
```

2022-07-24 10:18 UTC, DerMolly commented on src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap
> +      class="splitter "
```suggestion
      class="splitter"
```

2022-07-24 10:18 UTC, DerMolly commented on src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap
> +      class="splitter "
```suggestion
      class="splitter"
```

2022-07-24 10:18 UTC, DerMolly commented on src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap
> +      class="splitter "
```suggestion
      class="splitter"
```

2022-07-24 10:18 UTC, DerMolly commented on src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap
> +      class="splitter "
```suggestion
      class="splitter"
```

2022-07-24 10:18 UTC, DerMolly commented on src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap
> +      class="splitter "
```suggestion
      class="splitter"
```

2022-07-24 10:18 UTC, DerMolly commented on src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap
> +      class="splitter "
```suggestion
      class="splitter"
```

2022-07-24 10:18 UTC, DerMolly commented on src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap
> +      class="splitter "
```suggestion
      class="splitter"
```

2022-07-24 10:18 UTC, DerMolly commented on src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap
> +      class="splitter "
```suggestion
      class="splitter"
```

2022-07-24 10:26 UTC, mrdrogdrog requested changes

2022-07-24 10:26 UTC, mrdrogdrog commented on src/components/editor-page/splitter/splitter.tsx
> +        className={`${styles['splitter']} ${!showRight ? 'd-none' : ''}`}
Maybe change this to 
```suggestion
        className={`${styles['splitter']}${!showRight ? ' d-none' : ''}`}
```
to get rid of that trailing whitespace

2022-07-24 12:39 UTC, mrdrogdrog approved these changes

2022-07-24 19:18 UTC, DerMolly approved these changes

2022-07-24 19:22 UTC, merged