Table of contents test
hedgedoc/react-client pull request #2242
Opened 2022-07-27 20:14 UTC by mrdrogdrog

### Component/Part
Table of contents

### Description
This PR adds a memorized hook for the AST to React Element conversion.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### Related Issue(s)
Fixes #2180

2022-07-28 07:37 UTC, DerMolly requested changes

2022-07-28 07:37 UTC, DerMolly commented on src/components/editor-page/table-of-contents/use-build-react-dom-from-toc-ast.tsx
> +export const useBuildReactDomFromTocAst = (toc: TocAst, maxDepth: number, baseUrl?: string) => {
```suggestion
export const useBuildReactDomFromTocAst = (toc: TocAst, maxDepth: number, baseUrl: string) => {
```

2022-07-28 07:37 UTC, DerMolly commented on src/components/editor-page/table-of-contents/use-build-react-dom-from-toc-ast.tsx
>    baseUrl?: string
```suggestion
  baseUrl: string
```

2022-07-28 18:04 UTC, DerMolly approved these changes

2022-07-30 12:51 UTC, ErikMichelson requested changes

2022-07-30 12:51 UTC, ErikMichelson commented on src/components/editor-page/table-of-contents/use-build-react-dom-from-toc-ast.tsx
> +export const useBuildReactDomFromTocAst = (toc: TocAst, maxDepth: number, baseUrl: string) => {
ESDoc missing

2022-07-30 23:02 UTC, ErikMichelson approved these changes

2022-07-30 23:04 UTC, merged