Decrease docker image size
hedgedoc/react-client pull request #2261
Opened 2022-07-31 19:39 UTC by mrdrogdrog

### Component/Part
Docker image

### Description
This PR decreases the size of the docker image by:
- using alpine
- using the optimized standalone build.

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

2022-07-31 19:39 UTC, ErikMichelson approved these changes

2022-07-31 19:40 UTC, DerMolly approved these changes

2022-07-31 22:18 UTC, ErikMichelson requested changes
The latest changes without the chown break the builds.

```
Error: Cannot find module 'next/dist/server/next-server'
Require stack:
- /app/server.js
```

See also the mixed directory/file ownerships:
```
/app $ ls -lah
total 44K
drwxr-xr-x    1 node     node        4.0K Jul 31 22:07 .
drwxr-xr-x    1 root     root        4.0K Jul 31 22:19 ..
-rw-r--r--    1 node     node          31 Jul 31 22:06 .env.production
drwxr-xr-x    1 node     node        4.0K Jul 31 22:07 .next
drwxr-xr-x    3 node     node        4.0K Jul 31 22:06 .yarn
drwxr-xr-x    2 node     node        4.0K Jul 31 22:06 locales
-rw-r--r--    1 root     root        6.5K Jul 31 22:02 package.json
drwxr-xr-x    4 root     root        4.0K Jul 31 22:07 public
-rw-r--r--    1 node     node        3.0K Jul 31 22:06 server.js
drwxr-xr-x    3 node     node        4.0K Jul 31 22:06 src
```

2022-08-01 07:47 UTC, DerMolly commented on Dockerfile
> +COPY --from=builder /app/package.json ./package.json
```suggestion
COPY --from=builder --chown=node:node /app/public ./public
COPY --from=builder --chown=node:node /app/package.json ./package.json
```

2022-08-01 13:51 UTC, ErikMichelson approved these changes

2022-08-01 13:51 UTC, merged