Note Loading Boundary: Replace redirect with refetch from API
hedgedoc/react-client pull request #2275
Opened 2022-08-08 22:05 UTC by mrdrogdrog

### Component/Part
Note Loading Boundary

### Description
If the note loading boundary creates a note then it tries to redirect the browser to the new URL to force a reload and load the editor. But since the current URL and the redirection URL are the same nothing happens. This PR modifies the boundary to do a refetch from the API instead.

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

2022-08-09 03:04 UTC, DerMolly requested changes

2022-08-09 03:04 UTC, DerMolly commented on src/components/common/note-loading-boundary/note-loading-boundary.tsx
> +    doFetch()
This name is not to descriptive. I suggest `loadNoteFromServer`

2022-08-09 22:58 UTC, DerMolly approved these changes

2022-08-13 12:32 UTC, ErikMichelson approved these changes

2022-08-13 12:32 UTC, merged