feat(window post message communicator): Add uuid to frames
hedgedoc/react-client pull request #2416
Opened 2022-10-05 20:16 UTC by mrdrogdrog

### Component/Part
Window post message communicator

### Description
This PR adds uuids to identify and separate multiple renderers on one page

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

2022-10-05 20:20 UTC, DerMolly requested changes

2022-10-05 20:20 UTC, DerMolly commented on src/components/editor-page/render-context/editor-to-renderer-communicator-context-provider.tsx
> +import { v4 } from 'uuid'
```suggestion
import { v4 as uuid } from 'uuid'
```

2022-10-05 20:20 UTC, DerMolly commented on src/components/editor-page/render-context/editor-to-renderer-communicator-context-provider.tsx
> +  const communicator = useMemo<EditorToRendererCommunicator>(() => new EditorToRendererCommunicator(v4()), [])
```suggestion
  const communicator = useMemo<EditorToRendererCommunicator>(() => new EditorToRendererCommunicator(uuid()), [])
```

2022-10-05 20:24 UTC, DerMolly approved these changes

2022-10-07 10:55 UTC, ErikMichelson approved these changes

2022-10-07 21:48 UTC, merged