Settings dialog
hedgedoc/react-client pull request #2521
Opened 2022-11-11 21:54 UTC by mrdrogdrog

### Component/Part
Settings

### Description
This PR adds a settings modal

### Steps

- [x] Added implementation
- [ ] Added / updated tests
- [ ] Added / updated documentation
- [ ] Extended changelog
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### Related Issue(s)

2022-11-11 23:12 UTC, ErikMichelson requested changes
Shouldn't the settings button be available in the appbar on the intro/history pages as well to allow changing language and dark mode?

2022-11-11 23:12 UTC, ErikMichelson commented on src/components/layout/settings-dialog/utils/on-off-button-group.tsx
> +export const OnOffButtonGroup: React.FC<OnOffButtonGroupProps> = ({ onSelect, value }) => {
This component probably should be unit tested

2022-11-13 19:29 UTC, ErikMichelson approved these changes

2022-11-15 21:06 UTC, DerMolly approved these changes

2022-11-15 21:09 UTC, merged