fix anchor links
hedgedoc/react-client pull request #754
Opened 2020-11-14 08:49 UTC by DerMolly

### Component/Part
In the html renderer output the link icon should be visible, when hovering over a header.

### Description
This PR fixes the visibility of the link icon, when hovering over a header.

### Steps

- [x] added implementation
- [ ] added / updated tests
- [ ] added / updated documentation
- [ ] extended changelog

### Related Issue(s)

2020-11-14 22:18 UTC, mrdrogdrog requested changes

2020-11-14 22:18 UTC, mrdrogdrog commented on src/components/markdown-renderer/markdown-renderer.scss
> +    & a.heading-anchor {
The & here is redundant

2020-11-15 12:31 UTC, DerMolly commented on src/components/markdown-renderer/markdown-renderer.scss
> +    & a.heading-anchor {
fixed

2020-11-15 19:55 UTC, ErikMichelson approved these changes

2020-11-15 20:22 UTC, mrdrogdrog approved these changes

2020-11-15 20:23 UTC, merged