Improve readme
hedgedoc/react-client pull request #900
Opened 2020-12-31 17:32 UTC by mrdrogdrog

### Component/Part
README.md

### Description
This PR fixes a wrong command in the README and rewords the section about the production build.

### Steps

- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

2020-12-31 19:25 UTC, DerMolly approved these changes

2021-01-01 19:57 UTC, ErikMichelson requested changes
Although these change requests are incidentals, I'd like to follow our branding guide (in terms of capitalization) in our own project.

2021-01-01 19:57 UTC, ErikMichelson commented on README.md
> +    - `yarn start:for-real-backend` - Expects [a hedgedoc backend server](https://github.com/hedgedoc/hedgedoc/tree/develop) running under [http://localhost:3000](http://localhost:3000))
```suggestion
    - `yarn start:for-real-backend` - Expects [a HedgeDoc backend server](https://github.com/hedgedoc/hedgedoc/tree/develop) running under [http://localhost:3000](http://localhost:3000))
```

2021-01-01 19:57 UTC, ErikMichelson commented on README.md
> +    - `yarn start` - Calls only mocked version of the api. Doesn't need a hedgedoc backend.
```suggestion
    - `yarn start` - Calls only mocked version of the api. Doesn't need a HedgeDoc backend.
```

2021-01-02 09:45 UTC, mrdrogdrog commented on README.md
> +    - `yarn start` - Calls only mocked version of the api. Doesn't need a hedgedoc backend.
done

2021-01-02 09:45 UTC, mrdrogdrog commented on README.md
> +    - `yarn start:for-real-backend` - Expects [a hedgedoc backend server](https://github.com/hedgedoc/hedgedoc/tree/develop) running under [http://localhost:3000](http://localhost:3000))
done

2021-01-02 10:32 UTC, ErikMichelson approved these changes

2021-01-02 11:06 UTC, merged