Fix yaml metadata and document title not resetting on deletion
hedgedoc/react-client pull request #915
Opened 2021-01-06 15:27 UTC by ErikMichelson

### Component/Part
redux states and title extraction logic

### Description
This PR fixes the fact that yaml-metadata as well as the first heading for the title are cached for too long even if the document has no content anymore.

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

2021-01-06 16:37 UTC, mrdrogdrog requested changes
There is still a bug that causes the "yaml data invalid" message to stay if I remove a document with an invalid frontmatter

2021-01-07 15:04 UTC, ErikMichelson commented
We update the error boolean in the callback of the markdown-it-frontmatter plugin. It seems that this callback is never fired when there's no frontmatter thus the boolean doesn't get updated. I'm currently looking into how to resolve this.

2021-01-07 15:05 UTC, mrdrogdrog commented
maybe we should merge https://github.com/hedgedoc/react-client/pull/916 before this pr?

2021-01-07 15:06 UTC, ErikMichelson commented
As the markdown-it-frontmatter plugins runs on every content change of the whole markdown-content, we could disable this boolean on every content change via a useEffect prior to the plugin running. Hm, sounds a little hacky but maybe worth trying?

2021-01-07 15:06 UTC, ErikMichelson commented
Yes

2021-01-07 15:10 UTC, mrdrogdrog commented
Set yamlerror 

> As the markdown-it-frontmatter plugins runs on every content change of the whole markdown-content, we could disable this boolean on every content change via a useEffect prior to the plugin running. Hm, sounds a little hacky but maybe worth trying?

Well. How about this: When rendering a document we assume that there are no errors. If there are errors (the callback will get fired) we set a boolean (a ref or var) to true. After the rendering we check if the value is different from the current state and change it if necessary.

2021-01-07 15:11 UTC, mrdrogdrog commented
wow. deja vu. Don't we do that already somewhere? o.ö

2021-01-07 15:27 UTC, ErikMichelson commented
Isn't that the same thing I meant but just a bit more complex?

2021-01-07 15:28 UTC, mrdrogdrog commented
Don't do unnecessary state changes. Every state change triggers a rerender!

2021-01-07 15:29 UTC, ErikMichelson commented
You're right with that, I forgot that we need to use a state there.

2021-01-07 16:03 UTC, mrdrogdrog approved these changes

2021-01-07 16:27 UTC, DerMolly approved these changes

2021-01-07 16:38 UTC, merged