fixed title extraction to exclude latex code, but include rendered latex
hedgedoc/react-client pull request #946
Opened 2021-01-11 21:57 UTC by DerMolly

### Component/Part
title extraction

### Description
This PR improves the title extraction to leave out latex code, but include latex output.
e.g
```
# $\alpha$-foo
```
puts `α-foo` as the title

### Steps

- [x] Added implementation
- [x] Added / updated tests
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### Related Issue(s)
concerns #815

2021-01-11 22:30 UTC, mrdrogdrog approved these changes

2021-01-11 23:18 UTC, ErikMichelson requested changes
This seems not to be working properly.

To reproduce:
1. Write `#$\alpha$-foo` in exact that order of letter
2. Select the word `alpha` and replace it with `beta`
3. The preview is updated successfully, but the title shows `\bet-foo`

The CI btw has "Loading..." in the title instead of the character.

2021-01-12 07:35 UTC, DerMolly commented
> 1. Write `# $\alpha$-foo` in exact that order of letters
> 
> 2. Select the word `alpha` and replace it with `beta`
> 
> 3. The preview is updated successfully, but the title shows `\bet-foo`
> 
> 
> 
> The CI btw has "Loading..." in the title instead of the character.

Yes the test is not optimal currently.
We found out yesterday, that this seems to be a problem with the renderer and how it works. It needs some rerenders to have the latex code translated in the DOM. And I forgot to account for that in the test as it worked locally.

2021-01-12 08:15 UTC, mrdrogdrog commented
Let me elaborate:

KaTeX is an external (quite big) library which gets lazy loaded. While the browser fetches the code, a placeholder (`<span>Loading...</span>`) is shown.
The title gets extracted by a `useEffect` that is bound to the markdown source code. Therefore after the first rendering the effect only sees the placeholder (because katex isn't loaded yet)  and extracts the "Loading...". If you THEN change the markdown content again the effect gets triggered and sees the correct katex code.

2021-01-12 08:22 UTC, mrdrogdrog commented
It also seems like katex does some async rendering. I guess the component works the same way we use for mermaid. (Defining a container in react and passing this reference to the katex lib). That would explain why there is broken code in the title sometimes. We have a race condition between the effect and the katex lib.
Unfortunately there isn't much we can do about that :/

2021-01-12 08:23 UTC, DerMolly commented
Didn't we add a postRender method, we could use? But that also doesn't catch the async rendered stuff, does it?

2021-01-12 08:26 UTC, mrdrogdrog commented
The "postRender" is the useEffect. Effects are always triggered after the rendering. And yes, that wouldn't catch the async katex rendering.

2021-01-12 08:27 UTC, mrdrogdrog commented
We could watch the HTML-DOM for changes and trigger the effect again. But I don't think, that it's worth it.

2021-01-12 16:32 UTC, ErikMichelson approved these changes

2021-01-12 17:18 UTC, merged