removed frontmatter types as the package comes with it own types now
hedgedoc/react-client pull request #949
Opened 2021-01-14 15:35 UTC by DerMolly

### Component/Part
types

### Description
This PR replaces types for:
- markdown-it-frontmatter
- markdown-it-plantuml

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### Related Issue(s)
see #656

2021-01-14 18:42 UTC, mrdrogdrog requested changes

2021-01-14 18:42 UTC, mrdrogdrog commented on yarn.lock
> -    midi "git+https://github.com/paulrosen/MIDI.js.git#abcjs"
yarn again.. *sigh*

2021-01-14 18:59 UTC, DerMolly commented on yarn.lock
> -    midi "git+https://github.com/paulrosen/MIDI.js.git#abcjs"
argh

2021-01-14 19:17 UTC, mrdrogdrog approved these changes

2021-01-15 21:49 UTC, ErikMichelson approved these changes

2021-01-15 22:16 UTC, merged